# If this error throws when building the image from this Dockerfile:
# 'rpc error: code = Unknown desc = failed to fetch anonymous token: 
# unexpected status: 401 Unauthorized'
# You might set up your enviroment variables to 0:
# COMPOSE_DOCKER_CLI_BUILD=0
# DOCKER_BUILDKIT=0

# Create a Tensorflow image with GPU support
FROM nvcr.io/nvidia/tensorflow:21.09-tf2-py3

# Install OS dependencies
RUN apt-get update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install transformers

# Set working dir
RUN mkdir -p /usr/src/sentiment_analysis 
WORKDIR /usr/src/sentiment_analysis

# Copy source code and models
COPY classify_tf.py /usr/src/sentiment_analysis
RUN mkdir -p /usr/src/sentiment_analysis/models
COPY models/distilbert-base-uncased-finetuned-sst-2-english /usr/src/sentiment_analysis/models/distilbert-base-uncased-finetuned-sst-2-english

# Set enviroment variables
RUN mkdir /usr/src/sentiment_analysis/cache
ENV TRANSFORMERS_CACHE=/usr/src/sentiment_analysis/cache

# Configure entrypoint
ENTRYPOINT ["python3", "classify_tf.py"] 